Support release or beta version filter
RobotsAndPencils/XcodesApp pull request #153
Opened 2021-09-15 17:12 UTC by Binlogo

Implement #151 

Screenshots:

<img width="1027" alt="Xcodes filter - all" src="https://user-images.githubusercontent.com/7845507/133478721-ce2bef7c-d0ee-4729-9148-bc7fd841a04c.png">

<img width="1027" alt="Xcodes filter - release only" src="https://user-images.githubusercontent.com/7845507/133478547-c55c77c0-709b-48b3-a7a7-eccdcc54fbaa.png">

<img width="1027" alt="Xcodes filter - beta only" src="https://user-images.githubusercontent.com/7845507/133478705-ef7311c3-c234-447f-96fd-38504cb6dec3.png">

2021-09-15 18:19 UTC, MattKiazyk requested changes
Thanks @Binlogo! An awesome addition to Xcodes!

One quick change I'm going to request is making the filters be an `AND` instead of an `OR` so that there's no confusion.

2021-09-15 18:19 UTC, MattKiazyk commented on Xcodes/Frontend/XcodeList/XcodeListView.swift
> +            xcodes = appState.allXcodes.filter { $0.installState.installed }
```suggestion
            xcodes = xcodes.filter { $0.installState.installed }
```
I think it would be better if the `isInstalledOnly` is on, we filter with `AND` instead of `OR`, so that the user can use both filters.

2021-09-16 00:26 UTC, Binlogo commented on Xcodes/Frontend/XcodeList/XcodeListView.swift
> +            xcodes = appState.allXcodes.filter { $0.installState.installed }
Good to go, this is my purpose too, I missed it.

2021-09-16 14:44 UTC, MattKiazyk approved these changes

2021-09-16 14:45 UTC, merged