Adding Chinese-Simplified localizations.
RobotsAndPencils/XcodesApp pull request #222
Opened 2022-05-14 17:05 UTC by megabitsenmzq

Full translation for Chinese-Simplified.

2022-05-14 17:48 UTC, iXerol requested changes

2022-05-14 17:48 UTC, iXerol commented on Xcodes/Resources/zh-Hans.lproj/Localizable.strings
> +"CreateSymLink" = "以 Xcode.app 创建短链接";
「短链接」不恰当，常用翻译应为「符号链接」「软链接」（前者更规范）

2022-05-14 17:48 UTC, iXerol commented on Xcodes/Resources/zh-Hans.lproj/Localizable.strings
> +"Menu.GitHubRepo" = "Xcodes GitHub Repo";
与下文中这句不统一。
`"GithubRepo" = "GitHub 仓库";`

2022-05-14 17:48 UTC, iXerol commented on Xcodes/Resources/zh-Hans.lproj/Localizable.strings
> +"SignIn" = "登陆";
「登录」，多处相同问题

2022-05-14 18:17 UTC, megabitsenmzq commented on Xcodes/Resources/zh-Hans.lproj/Localizable.strings
> +"CreateSymLink" = "以 Xcode.app 创建短链接";
这个是我打错了，一会改一下。

2022-05-18 14:33 UTC, yuzhouwww commented
我正准备提 PR。。。😭

2022-05-18 14:52 UTC, yuzhouwww commented on Xcodes/Resources/en.lproj/Localizable.strings
> +"AutomaticallyCreateSymbolicLink" = "Automatically create symbolic link to Xcode.app";
you can also fix this typo in other localizations

2022-05-18 14:52 UTC, yuzhouwww commented on Xcodes/Resources/zh-Hans.lproj/Localizable.strings
> +"InstallationStepDescription" = "第%1$d步，共%2$d步：%3$@";
I prefer "进度 1/6: 下载中", more brief compared to "第 1 步，共 6 步: 下载中"

2022-05-18 14:52 UTC, yuzhouwww commented on Xcodes/Resources/zh-Hans.lproj/Localizable.strings
> +"DownloadingPercentDescription" = "正在下载：已完成%d%%";
"已完成" is unnecessary here

2022-05-19 03:32 UTC, megabitsenmzq commented on Xcodes/Resources/zh-Hans.lproj/Localizable.strings
> +"InstallationStepDescription" = "第%1$d步，共%2$d步：%3$@";
This changes the sentence too much. I always want to keep the structure from the source language as I can.

2022-05-19 03:33 UTC, megabitsenmzq commented on Xcodes/Resources/en.lproj/Localizable.strings
> +"AutomaticallyCreateSymbolicLink" = "Automatically create symbolic link to Xcode.app";
I will check it in other languages when I have time this week.

2022-05-19 03:35 UTC, megabitsenmzq commented on Xcodes/Resources/zh-Hans.lproj/Localizable.strings
> +"DownloadingPercentDescription" = "正在下载：已完成%d%%";
As I mentioned above, I want to keep the structure from the source language as I can. Also, if "已完成" is unnecessary, the same words in English strings will be unnecessary too. So I kinda want to keep this.

2022-05-20 02:58 UTC, MattKiazyk commented
I've closed  #228 as a duplicate of this PR but @hdcola and @Sichengthebest if you have any comments on @megabitsenmzq implementation, please feel free to make a comment.

2022-05-25 03:03 UTC, MattKiazyk commented
@megabitsenmzq is this ready for review? 

There's a conflict because we've had a few new languages all updating the same file. If you could fix that up, or let me know it's ready and I can fix up.

2022-05-27 03:24 UTC, MattKiazyk commented
Thanks @megabitsenmzq and all!

2022-05-27 03:24 UTC, merged