German translation added
RobotsAndPencils/XcodesApp pull request #243
Opened 2022-06-08 12:53 UTC by drct

Added de.lproj folder containing Localizable.strings with German translation. No changes to Xcode's project file. First translation and github pull request for me, so I hope everything's alright. Cheers.

2022-06-13 13:28 UTC, MattKiazyk commented
Hey @drct looks like your missing some changes to the XcodeProj to include it? I was going to take your PR for German because you create it first and the dictionary is the exact same as https://github.com/RobotsAndPencils/XcodesApp/pull/245. If you're ok with it, I can take the other one instead, otherwise, could you fix it up to include those changes. Thanks

2022-06-13 15:39 UTC, drct commented
Thanks. I'll check it and update the XcodeProj.

2022-06-14 00:07 UTC, MattKiazyk requested changes
@drct Just one small change needed. Thanks!

2022-06-14 00:07 UTC, MattKiazyk commented on Xcodes/Resources/de.lproj/Localizable.strings
> +"DataSourceDescription" = "Die Apple-Datenquelle liest die Apple Developer-Website aus. Sie zeigt immer die neuesten Releases an, die verfügbar sind, ist allerdings etwas instabiler.\n\nXcode-Release
```suggestion
"DataSourceDescription" = "Die Apple-Datenquelle liest die Apple Developer-Website aus. Sie zeigt immer die neuesten Releases an, die verfügbar sind, ist allerdings etwas instabiler.\n\nXcode Releases ist eine inoffizielle Liste von Xcode-Veröffentlichungen. Sie wird als formatierte Daten bereitsgestellt, enthält Extrainformationen die nicht ohne weiteres von Apple erhältlich sind und ist mit höherer Wahrscheinlichkeit weiter verfügbar, sollte Apple seine Entwickler-Website neu gestalten.";
```
This isn't called out very well, but the attributed string is looking specifically for `Xcode Releases` here, so that string needs to be in this value.

2022-06-14 06:55 UTC, drct commented
@MattKiazyk Created a commit with your suggestions.

2022-06-16 02:38 UTC, merged

2022-06-16 02:38 UTC, MattKiazyk commented
Thanks for contributing!