Correct Date format
RobotsAndPencils/XcodesApp pull request #251
Opened 2022-06-11 22:21 UTC by d-date

Thanks to localized by community, we found some incorrect date format localization. https://github.com/RobotsAndPencils/XcodesApp/pull/249#issuecomment-1152891477

Before:
<img width="960" alt="Screen Shot 2022-06-12 at 7 18 38" src="https://user-images.githubusercontent.com/20222809/173206653-93656498-2110-442b-9ebe-d074996f454a.png">

After:
<img width="961" alt="Screen Shot 2022-06-12 at 7 20 14" src="https://user-images.githubusercontent.com/20222809/173206692-919a36bb-7778-47c7-924e-cda1e23ee62f.png">

2022-06-12 20:51 UTC, d-date commented
Totally misunderstood how to use it. Now completely fixed at https://github.com/RobotsAndPencils/XcodesApp/pull/251/commits/e210050f815e11021bd9289502fbbdc5fc995bdb

Japan / Gregorian:
<img width="969" alt="Screen Shot 2022-06-13 at 5 49 09" src="https://user-images.githubusercontent.com/20222809/173253062-0896faad-b8b5-41f0-aac3-be81498f24f5.png">

Japan / Japanese:
<img width="967" alt="Screen Shot 0004-06-13 at 5 49 57" src="https://user-images.githubusercontent.com/20222809/173253086-c08b8ae5-ac4d-416b-b26b-5add9f8f73dc.png">

2022-06-13 04:01 UTC, MattKiazyk requested changes
Hey @d-date just some commit cleanup if you could! Thanks for making this change

2022-06-13 04:01 UTC, MattKiazyk commented on Xcodes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "repositoryURL": "https://github.com/sparkle-project/Sparkle",
Can you remove this commit? I know it may be an automatic thing but keep the PR to the change. thanks!

2022-06-13 04:01 UTC, MattKiazyk commented on com.robotsandpencils.XcodesApp.Helper/Info.plist
> +	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
Can you remove this commit? I know it may be an automatic thing but keep the PR to the change. thanks!

2022-06-13 04:01 UTC, MattKiazyk commented on Xcodes/Backend/DateFormatter+.swift
> +        formatter.dateFormat = dateFormat(fromTemplate: "yyMMddHHmm", options: 0, locale: Locale.autoupdatingCurrent)
👏 I learned something today - thanks for adding this!

2022-06-13 05:16 UTC, d-date commented
@MattKiazyk Done 👍

2022-06-13 13:17 UTC, MattKiazyk commented on Xcodes/Backend/DateFormatter+.swift
> +        formatter.dateFormat = dateFormat(fromTemplate: "yyMMddHHmm", options: 0, locale: Locale.autoupdatingCurrent)
@d-date as I slept on it, this date formatter will not work with the Apple data source - and receive the error:

<img width="261" alt="image" src="https://user-images.githubusercontent.com/1119565/173362076-5213ae29-f3ae-4b7a-9170-393ecec8c519.png">

Sorry about that. I do suggest creating new DateFormatters so that the front end UI can use them, separating the backend parse format vs the front.

2022-06-15 06:54 UTC, d-date commented on Xcodes/Backend/DateFormatter+.swift
> +        formatter.dateFormat = dateFormat(fromTemplate: "yyMMddHHmm", options: 0, locale: Locale.autoupdatingCurrent)
I'll make specific date formatter for parsing json😇

2022-06-16 01:47 UTC, d-date commented on Xcodes/Backend/DateFormatter+.swift
> +        formatter.dateFormat = dateFormat(fromTemplate: "yyMMddHHmm", options: 0, locale: Locale.autoupdatingCurrent)
https://github.com/RobotsAndPencils/XcodesApp/pull/251#issuecomment-1156295367

2022-06-16 03:02 UTC, merged

2022-06-16 03:02 UTC, MattKiazyk commented
Thanks again @d-date