move download settings to own PreferencePane
RobotsAndPencils/XcodesApp pull request #305
Opened 2022-10-05 19:06 UTC by leon-wolf

fixes #291 

- move downloads related settings to own preference pane

2022-11-09 04:38 UTC, MattKiazyk requested changes
@leon-wolf Thanks for this - looks super clean - just a fix up to make sure you add `DownloadPreferencePane` to the project

2022-11-09 04:38 UTC, MattKiazyk commented on Xcodes/Frontend/Preferences/DownloadPreferencePane.swift
> +struct DownloadPreferencePane: View {
Looks like `DownloadPreferencePane` wasn't added to the project.

2022-11-11 09:40 UTC, leon-wolf commented on Xcodes/Frontend/Preferences/DownloadPreferencePane.swift
> +struct DownloadPreferencePane: View {
should be added in the latest commit. I don't really know how it was not added :D

2022-11-11 15:33 UTC, MattKiazyk approved these changes

2022-11-11 15:34 UTC, MattKiazyk commented
Thanks @leon-wolf for all the work!

2022-11-11 15:34 UTC, merged