add error message when trying to uninstall Xcode if file not found
RobotsAndPencils/XcodesApp pull request #306
Opened 2022-10-06 06:45 UTC by leon-wolf

resolves #144:

- check if file exists, which the user is trying to delete
- throw FileNotFound Error when file is not found. Localized in German and English for now.

2022-11-09 05:58 UTC, MattKiazyk requested changes
Nice clean change  - thanks!

Just fix up adding it into the project

2022-11-09 05:58 UTC, MattKiazyk commented on Xcodes/Backend/FileError.swift
> +import Foundation
Same as your other PR - this needs to be added to the project.

2022-11-11 15:34 UTC, MattKiazyk commented
@leon-wolf sorry with the last merge there's a conflict with new files. When you have a moment can you fix it up?

2022-11-11 16:19 UTC, leon-wolf commented
> @leon-wolf sorry with the last merge there's a conflict with new files. When you have a moment can you fix it up?

yeah sure. no problem :)

2022-11-11 17:27 UTC, MattKiazyk approved these changes

2022-11-11 17:27 UTC, merged